title: Data Undigital
description: "Data Undigital helps public and private organisations design, fund and deliver complex data-enabled products, platforms and programmes. Deep expertise in IoT, AI, data spaces and collaborative R&D."
author: Alex Gluhak
url: "https://data-undigital.com"
baseurl: ""

permalink: /blog/:year/:month/:day/:title/

markdown: kramdown
highlighter: rouge

plugins:
  - jekyll-sitemap

exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - functions/
